/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstanceUuidRouteImport } from './routes/instance.$uuid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstanceUuidRoute = InstanceUuidRouteImport.update({
  id: '/instance/$uuid',
  path: '/instance/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instance/$uuid': typeof InstanceUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instance/$uuid': typeof InstanceUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instance/$uuid': typeof InstanceUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/instance/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/instance/$uuid'
  id: '__root__' | '/' | '/instance/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstanceUuidRoute: typeof InstanceUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instance/$uuid': {
      id: '/instance/$uuid'
      path: '/instance/$uuid'
      fullPath: '/instance/$uuid'
      preLoaderRoute: typeof InstanceUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstanceUuidRoute: InstanceUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
